/*
 * BrokerGui.java
 *
 * Created on January 12, 2007, 3:55 PM
 */

package price.client.gui;

/**
 *
 * @author  vp200359
 */

import java.util.logging.Logger;

import price.common.model.IPriceModel;
import price.common.controller.IPriceController;
//import price.common.model.Customer;
//import price.common.model.Portfolio;
import price.common.model.PriceModel;

public class PriceGui extends javax.swing.JFrame implements GuiLogService {
    // private BrokerController brokerController;
    private IPriceController controller;
    private IPriceModel model;
    private String logName = "Price Tool"; 
    private Logger logger = Logger.getLogger(logName); 
    private IPriceModelPanel[] panels= new IPriceModelPanel[10];        

    /** Creates new form BrokerGui */
    public PriceGui() {
        initComponents();
        logger.addHandler(new GuiLogHandler(this));
    }

    public PriceGui(IPriceModel model) { 
        this(); 
        this.model = model;
        //* Code to create and add the customer panel to the panels array.
        panels[0] = customerPanel1;
        panels[0].registerModel(model);
        //* Code to build AllCustomersPanel
        panels[1] = allCustomerTablePanel1;
        panels[1].registerModel(model);
    }

    public void addController(IPriceController controller){
        // brokerController = controller;
        this.controller = controller;
        for(int i=0; panels[i] != null; i++)
            panels[i].registerController(controller);
    }

    public void displayObject(Object obj) {
        if (obj == null){
            System.out.println("Object display is null.");
            return;
        }
        if (obj instanceof PriceModel){
            panels[0].display(obj);
            panels[1].refresh();
        }
       /* if (obj instanceof Customer[]){
            panels[1].display(obj);
        }
        if (obj instanceof Portfolio){
            //TBD
        }
       if (obj instanceof PriceModel[]){
            //TBD
        }*/
        if (obj instanceof Exception) {
            // log the exception
            logger.severe(obj.toString());
        }
    }
    
    public void setLog(String log){
        jTextArea1.setText(log);
    }
    
    public void addToLog(String newLogEvent){
        jTextArea1.append(newLogEvent);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        customerPanel1 = new PricePanel();
        allCustomerTablePanel1 = new AllPricesTablePanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BrokerTool");
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.addTab("Price Details", customerPanel1);

        jTabbedPane1.addTab("All Prices", allCustomerTablePanel1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Log Panel"));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private AllPricesTablePanel allCustomerTablePanel1;
    private PricePanel customerPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}