package price.client.gui;
import price.common.model.IPriceModel;
import price.common.controller.IPriceController;
import price.common.model.PriceModel;
/*
 * CustomerPanel.java
 *
 * Created on December 11, 2006, 2:38 PM
 */

/**
 *
 * @author  vp200359
 */
public class PricePanel extends javax.swing.JPanel implements IPriceModelPanel {
    IPriceModel model;
    IPriceController controller;
    String id;
    float price;
    //custAddr;
    /** Creates new form CustomerPanel */
    public PricePanel() {
        initComponents();
    }
    
    public void registerController(IPriceController controller) {
        this.controller = controller;
    }
    
    public void registerModel(IPriceModel model) {
        this.model = model;
    }
    public void refresh() {
        // get customer id from appropriate Textfield
        try{
            // (if not blank) get the corresponding customer object from the 
            // model show the customer details on the panel
            if(idTf.getText().trim() != ""){
                //**1 Get customer object corresponding to idTf from model and
                //    assign to cust.                
                PriceModel cust=model.getPrice((idTf.getText()));
                //**2 Update addrTf from value in cust
                idTf.setText(cust.getSymbol());
                //**3 Update nameTf from value in cust
            priceTf.setText(String.valueOf(cust.getPrice()));
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    public void display(Object obj){
    	PriceModel  cust;
        if (obj instanceof PriceModel) {
            cust = (PriceModel) obj;
            id = idTf.getText().trim();
            // if cust.getId equals custId on the CustomerPanel
            // then display the customer object on the CustomerPanel
            if (id.equals(cust.getSymbol())){
               priceTf.setText(String.valueOf(cust.getPrice()));
                //nameTf.setText(cust.getName());
            }
        }
    }

    public javax.swing.JPanel getPanel() {
        return this;
    }
    
    // helper methods
    protected String getPriceId(){
        return idTf.getText().trim();
    }
    
  /* protected String getCustName(){
        return nameTf.getText().trim();
    }*/
    
    protected float getPricePrice(){
        return Float.valueOf(priceTf.getText().trim());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
   //    nameLb = new javax.swing.JLabel();
        idLb = new javax.swing.JLabel();
        priceLb = new javax.swing.JLabel();
  //      nameTf = new javax.swing.JTextField();
        idTf = new javax.swing.JTextField();
        priceTf = new javax.swing.JTextField();
        getBt = new javax.swing.JButton();
        updBt = new javax.swing.JButton();
        addBt = new javax.swing.JButton();
        delBt = new javax.swing.JButton();

       // nameLb.setText("Customer Name");

        idLb.setText("Identity");

        priceLb.setText("Price");

        getBt.setText("Get Price");
        getBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBtActionPerformed(evt);
            }
        });

        updBt.setText("Update Price");
        updBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBtActionPerformed(evt);
            }
        });

        addBt.setText("Add Price");
        addBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtActionPerformed(evt);
            }
        });

        delBt.setText("Delete Price");
        delBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(getBt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .add(addBt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(delBt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .add(updBt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               //             .add(nameLb, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .add(idLb, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(idTf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                   /*    .add(nameTf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 188, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))*/
                    .add(layout.createSequentialGroup()
                        .add(priceLb, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(priceTf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                .addContainerGap())
   );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                    //    .add(nameTf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(idTf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(idLb))))
                  //  .add(nameLb))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(priceLb)
                    .add(priceTf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(getBt)
                    .add(updBt))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(delBt)
                    .add(addBt))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtActionPerformed
        // TODO add your handling code here:
        String buttonName = evt.getActionCommand();
        String Id = getPriceId();
        PriceModel cust = new PriceModel(getPriceId(), getPricePrice()); //getCustName(), getCustAddr());
        System.out.println("CustomerListener buttonName = " + buttonName);
        controller.handleDeletePriceGesture(cust);
    }//GEN-LAST:event_delBtActionPerformed

    private void updBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtActionPerformed
        // TODO add your handling code here:
        String buttonName = evt.getActionCommand();
       String Id = getPriceId();
        PriceModel cust = new PriceModel(getPriceId(), getPricePrice()); //getCustName(), getCustAddr());
        System.out.println("CustomerListener buttonName = " + buttonName);
        controller.handleUpdatePriceGesture(cust);
    }//GEN-LAST:event_updBtActionPerformed

    private void addBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtActionPerformed
        // TODO add your handling code here:
        String buttonName = evt.getActionCommand();
        String custId = getPriceId();
        PriceModel cust = new PriceModel(getPriceId(), getPricePrice()); //getCustName(), getCustAddr());
        System.out.println("CustomerListener buttonName = " + buttonName);
        controller.handleAddPriceGesture(cust);
    }//GEN-LAST:event_addBtActionPerformed

    private void getBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBtActionPerformed
        // TODO add your handling code here:
        String buttonName = evt.getActionCommand();
        String Id = idTf.getText().trim();
        // Customer cust = new Customer(getCustId(), getCustName(), getCustAddr());
        System.out.println("CustomerListener buttonName = " + buttonName);
        controller.handleGetPriceGesture(Id);
    }//GEN-LAST:event_getBtActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBt;
  private javax.swing.JLabel priceLb;
    private javax.swing.JTextField priceTf;
    private javax.swing.JButton delBt;
    private javax.swing.JButton getBt;
    private javax.swing.JLabel idLb;
    private javax.swing.JTextField idTf;
 //   private javax.swing.JLabel nameLb;
   // private javax.swing.JTextField nameTf;
    private javax.swing.JButton updBt;
    // End of variables declaration//GEN-END:variables
    
}